version: 2
updates:
  - package-ecosystem: docker
    directory: /ingestor
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: pip
    directory: /ingestor
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /triplestore
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: maven
    directory: /triplestore
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /search
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /explore
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: npm
    directory: /explore
    schedule:
      interval: daily
      time: '07:00'
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: docker
    directory: /mcp
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: pip
    directory: /mcp
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '07:00'
    allow:
      - dependency-type: all
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
